### ISSUE TITLE
Review of ANS Annual meeting 2021 summary

### ISSUE THREAD

**Issue by robfairh** [robfairh/npre555-cp03#2]
This issue can be closed when @katyhuff has reviewed the following document:

[fairhurst-ans-summary.pdf](https://github.com/robfairh/npre555-cp03/files/5898555/summary.pdf)

**Comment by katyhuff** [comment]
In the future, please assign me to the issue, rather than just tagging me. 

Regardless. This looks good to me. The only suggestion I have is that it is best practice to include an actual legend for all figures (with color patches). This is primarily because using red and green as the two main colors in a figure and describing colors by name in the caption both present challenges to colorblind readers.

**Comment by robfairh** [comment]
Thanks for reviewing. You are certainly right. I'll fix that!
